server:
  port: 8888

spring:
  application:
    name: springcloud-config-server
  # 连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/becauseoflife/SpringCloud-config.git
